import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

export async function GET(
  request: Request,
  { params }: { params: Promise<{ clientId: string }> }
) {
  const { clientId } = await params
  const session = await getServerSession(authOptions)
  
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Check Access
  let authorized = false;
  if(session.user.role === 'SUPER_ADMIN') authorized = true;
  if(session.user.role === 'PROJECT_MANAGER') {
     const user = await prisma.user.findUnique({ where: { id: session.user.id }, include: { clients: true }});
     if(user?.clients.some(c => c.id === clientId)) authorized = true;
  }

  if (!authorized) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const branches = await prisma.branch.findMany({
      where: {
        clientId: clientId
      },
      orderBy: { createdAt: 'desc' },
      include: {
        _count: {
          select: { maintenanceLogs: true }
        }
      }
    })

    return NextResponse.json(branches)
  } catch (error) {
    return NextResponse.json({ error: 'Error fetching branches' }, { status: 500 })
  }
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ clientId: string }> }
) {
  const { clientId } = await params
  const session = await getServerSession(authOptions)
  
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Check Access
  let authorized = false;
  if(session.user.role === 'SUPER_ADMIN') authorized = true;
  if(session.user.role === 'PROJECT_MANAGER') {
     const user = await prisma.user.findUnique({ where: { id: session.user.id }, include: { clients: true }});
     if(user?.clients.some(c => c.id === clientId)) authorized = true;
  }

  if (!authorized) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  try {
    const body = await request.json()
    const { name, address, latitude, longitude } = body

    const branch = await prisma.branch.create({
      data: {
        name,
        address,
        latitude: latitude ? parseFloat(latitude) : null,
        longitude: longitude ? parseFloat(longitude) : null,
        clientId: clientId
        // qrCode is automatically generated by default(uuid()) in schema
      }
    })

    return NextResponse.json(branch)
  } catch (error) {
    console.error("Error creating branch:", error)
    return NextResponse.json({ error: 'Error creating branch' }, { status: 500 })
  }
}
